### ISSUE TITLE
Avoid overwriting when several numbers are in the list

### ISSUE THREAD

**Issue by kgashok** [kgashok/elm-simple-json-decoding#10]
The **width** of the `ul` list needs to vary with the content. 
How to do this? Use CSS? 
![overwritinginfccelm](https://cloud.githubusercontent.com/assets/2399010/15986163/b855fa48-301e-11e6-9040-72692a731ecc.png)

**Comment by ddrdushy** [comment]
sample css
```css
#list{
    position: relative;
    width:100%;
    display: block;
}

#list li {
    width: 10%; /* nice 10 columns */
    float: left;
    padding: 0; /* should have zero paddng/margin */
    margin: 0;
}
```

HTML
```html
  <ul id="list">
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <li>hi</li>
    <ul>
```
